from game.events import GameEvents

KEY_DOWN = GameEvents.KEY_DOWN
KEY_UP = GameEvents.KEY_UP

MOUSE_BUTTON_DOWN = GameEvents.MOUSE_BUTTON_DOWN
MOUSE_BUTTON_UP = GameEvents.MOUSE_BUTTON_UP
MOUSE_MOTION = GameEvents.MOUSE_MOTION

MENU_PLAY = 'MENU.PLAY'
MENU_QUIT = 'MENU.QUIT'

EVENT_START = 'GAME.START'
EVENT_WIN = 'GAME.WIN'
EVENT_LOOSE = 'GAME.LOOSE'
