WIN_WIDTH = 640  #800
WIN_HEIGHT = 460  #640
DISPLAY = (WIN_WIDTH, WIN_HEIGHT)
PLAYER_POS = (WIN_WIDTH / 2, WIN_HEIGHT / 2)
MAP_POS = (0, 0)
BACKGROUND_COLOR = "#0099FF"
TITLE = "World Walker"
GRID_SIZE = 32

FRAME_RATE = 60
BACK_IMAGE_FILENAME = None
