UAF_RAND = "/cygdrive/c/Programs/Adv/AberMUD2/mud/uaf.rand"
ROOMS = "/cygdrive/c/Programs/Adv/AberMUD2/mud/TEXT/ROOMS/"
LOG_FILE = "/cygdrive/c/Programs/Adv/AberMUD2/mud/mud_syslog"
BAN_FILE = "/cygdrive/c/Programs/Adv/AberMUD2/mud/banned_file"
from .nologin import Nologin
RESET_T = "/cygdrive/c/Programs/Adv/AberMUD2/mud/reset_t"
from .reset_n import ResetN
RESET_DATA = "/cygdrive/c/Programs/Adv/AberMUD2/mud/reset_data"
MOTD = "/cygdrive/c/Programs/Adv/AberMUD2/mud/TEXT/gmotd2"
GWIZ = "/cygdrive/c/Programs/Adv/AberMUD2/mud/TEXT/gwiz"
HELP1 = "/cygdrive/c/Programs/Adv/AberMUD2/mud/TEXT/help1"
HELP2 = "/cygdrive/c/Programs/Adv/AberMUD2/mud/TEXT/help2"
HELP3 = "/cygdrive/c/Programs/Adv/AberMUD2/mud/TEXT/help3"
WIZLIST = "/cygdrive/c/Programs/Adv/AberMUD2/mud/TEXT/wiz.list"
CREDITS = "/cygdrive/c/Programs/Adv/AberMUD2/mud/TEXT/credits"
EXAMINES = "/cygdrive/c/Programs/Adv/AberMUD2/mud/EXAMINES/"
LEVELS = "/cygdrive/c/Programs/Adv/AberMUD2/mud/TEXT/level.txt"
PFL = "/cygdrive/c/Programs/Adv/AberMUD2/mud/user_file"
PFT = "/cygdrive/c/Programs/Adv/AberMUD2/mud/user_file.b"
from .exe import Exe
EXE2 = "/cygdrive/c/Programs/Adv/AberMUD2/mud/mud.1"
SNOOP = "/cygdrive/c/Programs/Adv/AberMUD2/mud/SNOOP/"
